# Generated by Django 3.2.12 on 2022-04-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('clicks', models.IntegerField()),
            ],
        ),
    ]
